config/routes.rb
Rails.application.routes.draw do

 get 'users/premium_to_standard'
 get 'users/standard_to_premium'

  devise_for :admins
  devise_for :users, controllers: {registration: "registrations"}
  resources :users, only: [] do
     post 'premium_to_standard' => 'users#premium_to_standard', as: :premium_to_standard
    post 'standard_to_premium' => 'users#standard_to_premium', as: :standard_to_premium

 end



  resources :wikis do
     resources :collaborators
   end

  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'welcome/index'
  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def new
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
  end

  def show
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
    @collaborator.user_id = params[:collaborator][:user_id]
    @collaborator.wiki_id = @wiki.id

    if @collaborator.save
      flash[:notice] = "Collaborator was added."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error adding the collaborator. Please try again."
      render :new
    end
  end

  def edit
    @collaborator = Collaborator.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.users.push(User.find(params[:wiki][:users]))

    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])
    user = @collaborator.user_id
    @collaborator = Collaborator.where(user_id: user, wiki_id: @wiki.id)

    if Collaborator.destroy(@collaborator.ids)
      flash[:notice] = "Collaborator was successfully deleted."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error deleting the collaborator."
      render :show
    end
  end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/_collaborator.html.erb
<%= content_tag :div, class: 'media', id: "collaborator-#{collaborator.id}" do %>
  <div class="media-body">
    <small>
      <%= User.find(collaborator.user_id).email %>
      <% if current_user.admin? || current_user == @wiki.user %>
        | <%= link_to "Delete", wiki_collaborator_path(@wiki, collaborator), method: :delete %>
      <% end %>
    </small>
  </div>
<% end %>

app/views/collaborators/new.html.erb
<h1>Add Collaborator</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for [@wiki, @collaborator] do |f| %>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label "Users" %>
          <%= f.select :user_id, options_from_collection_for_select(User.where.not(id: @wiki.users), :id, :email), {:class => 'form-control'} %>
        </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>