config/routes.rb
Rails.application.routes.draw do

 get 'users/premium_to_standard'
 get 'users/standard_to_premium'

  devise_for :admins
  devise_for :users, controllers: {registration: "registrations"}
  resources :users, only: [] do
     post 'premium_to_standard' => 'users#premium_to_standard', as: :premium_to_standard
    post 'standard_to_premium' => 'users#standard_to_premium', as: :standard_to_premium

 end



  resources :wikis do
     resources :collaborators
   end

  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'welcome/index'
  root 'welcome#index'
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators


  validates :user, presence: true
  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 5}, presence: true

  default_scope { order('created_at DESC') }
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  after_action :verify_authorized
  #if you forgot 'authorize @wiki' & you want to make sure your controller is still locked down
  #use this method - 'after_action :verify_authorized' - which pundit provides
  #It makes sure that you've called the authorize method in each and every1 of ur actions!
  # rails s error message = Pundit::AuthorizationNotPerformedError (WikisController): MEANS no1 called pundit's authorize method inside of that action!
  #Took from wikis_controller and placed into application_controller to make sure every single action, in our entire application, is verified for authorization!




  def index
    @wikis = Wiki.all
    authorize @wikis
  end



  def show #will automatically be authorized!!
    set_wiki
  end



  def new
    @wiki = Wiki.new
    authorize @wiki
  end



  def edit #will automatically be authorized!!
    set_wiki
    @users = User.all
  end



  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Your Wiki was published."
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error creating your Wiki. Please try again."
      render :new
    end
  end



  def update #will automatically be authorized!!
    set_wiki
    @wiki.assign_attributes(wiki_params)

    if @wiki.update(wiki_params)
      flash[:notice] = "Your Wiki was updated."
      redirect_to [@wiki]
    else
      flash[:error] = "There was an error updating your Wiki. Please try again."
      render :edit
    end
  end



  def destroy #will automatically be authorized!!
    set_wiki
     if @wiki.destroy
       flash[:notice] = "Wiki #{@wiki.title} was deleted."
     else
       flash.now[:alert] = "There was a Error deleting your Wiki."
       render :show
     end
    redirect_to wikis_path
    #redirecting to index action template "app/views/wikis/index.html.erb"
  end



   private
   #Add private methods to the bottom of the file.
   #Any method defined below private, will be private.


    def set_wiki
      @wiki = Wiki.find(params[:id])
      authorize @wiki
    end
    #When we set the wiki that means it will authorize automatically!!!!
    #This allows: destroy, update, edit, and show actions - will automatically be authorized!!
    #And the ones that have @wiki, inside of the action, u can lock those down, and that's it!


    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end

    def authorize_user
     wiki = Wiki.find(params[:id])

     unless current_user == wiki.user || current_user.admin?
       flash[:alert] = "You must be an Admin to do that."
       redirect_to [@wiki]
     end
   end
end

app/helpers/wikis_helper.rb
module WikisHelper

  def user_is_authorized_for_private?
    current_user.premium? || current_user.admin?
  end

  def user_is_authorized_for_edit?
    current_user
  end

  def user_is_authorized_for_delete?
    current_user && current_user.admin?
  end

  def user_is_authorized_for_collaborator_edit?
    @wiki.user || current_user.premium?
  end

  def wiki_has_collaborators?
    @wiki.collaborators.any?
  end

  def find_users()
    users = []
    collaborators = Collaborator.pluck(:user_id) # find all user_id's that are currently collaborators
    all_users = User.all
    all_users.each do |user|
      if !collaborators.include?(user.id)
        users << user # if user is not a collaborator, add to list
      end
    end
    users
    puts users
  end
end

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>

   <% if @wiki.errors.any? %>

     <div class="alert alert-danger">
       <h4><%= pluralize(@wiki.errors.count, "error") %>.</h4>
       <ul>
         <% @wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>

   <% end %>

   <%= form_group_tag(@wiki.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Plant title here" %>
   <% end %>

   <%= form_group_tag(@wiki.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Plant body here" %>
   <% end %>

   <% if user_is_authorized_for_private? -%>
      <div class="form-group">
        <%= f.check_box :private %>
        <%= f.label :private %>
      </div>
    <% end -%>

   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/wikis/_wiki.html.erb
<div class="media">
  <div class="media-body">
  <h4 class="media-heading" style="display:inline-block">
    <% if wiki.private? %>
      <%= link_to wiki.title, wiki, class: "private" %> <small>Private Wiki</small>
    <% else %>
      <%= link_to wiki.title, wiki %>
    <% end %>
    </h4>
     <small><%= link_to 'Show', wiki_path(wiki.id) if policy(wiki).show? %></small>
     <small><%= link_to 'Edit', edit_wiki_path(wiki.id) if policy(wiki).edit? %></small>
     <small><%= link_to 'Destroy', wiki_path(wiki.id),
      method: :delete,
      data: { confirm: 'Are you sure you want to delete this wiki?' } if policy(wiki).destroy? %></small>
  </div>
</div>

app/views/wikis/edit.html.erb
<div class="row f1-edit">
  <div class="col-md-9">
    <h1>Edit Wiki</h1>
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
  <div class="col-md-3 box-shaded">
    <h2>Markdown</h2>
    <small>
      <p># large header</p>
      <p>## medium header</p>
      <p>### small header</p>
      <p><strong>**bold**</strong></p>
      <p><em>*italic*</em></p>
      <p><mark>==highlight==</mark></p>
      <p><span style="text-decoration: line-through">~~strike through~~</span></p>
      <p>--- horizontal rule</p>
      <p>`code`</p>
      <p>Links: [linked text](https://linkurl)</p>
      <p><%= link_to "Markdown cheatsheet", "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet", class: "button-small" %><p>
    </small>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="f1">
  <div class="row">
    <div class="col-md-8">
      <% @wikis.each do |wiki| %>
        <%= render partial: "wiki", locals: { wiki: wiki } %>
      <% end %>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="row f1-new">
  <div class="col-md-9">
    <h1>New Wiki</h1>
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
  <div class="col-md-3 box-shaded">
    <h2>Markdown</h2>
    <small>
      <p># large header</p>
      <p>## medium header</p>
      <p>### small header</p>
      <p><strong>**bold**</strong></p>
      <p><em>*italic*</em></p>
      <p><mark>==highlight==</mark></p>
      <p><span style="text-decoration: line-through">~~strike through~~</span></p>
      <p>--- horizontal rule</p>
      <p>`code`</p>
      <p>Links: [linked text](https://linkurl)</p>
      <p><%= link_to "Markdown cheatsheet", "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet", class: "button-small" %><p>
    </small>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="f1">
  <%= link_to '<< back to the Forest', wikis_path %>
  <div class="row">
    <div class="col-md-8">
      <h2><%= @wiki.title %></h2>
      <small><%= markdown(@wiki.body).html_safe %></small>

      <% if @wiki.private? %>
        <div>
          <h3>Collaborators</h3>
          <%= render @wiki.collaborators %>
        </div>
      <% end %>

    </div>

    <div class="col-md-4">
      <p>&nbsp;</p>

      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <% if (current_user.admin? || (current_user.premium? && current_user == @wiki.user)) && @wiki.private? %>

        <%= link_to "Add Collaborator", new_wiki_collaborator_path(@wiki), class: 'btn btn-success' %>
      <% end %>


        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>

    </div>

    <div class="col-md-12 box-shaded">
      <h4>Creator</h4>
        <span class="glyphicon glyphicon-user"></span>
        <%= current_user.email %>
        <%= current_user.username %>
    </div>
  </div>
</div>