config/routes.rb
Rails.application.routes.draw do

 get 'users/premium_to_standard'
 get 'users/standard_to_premium'

  devise_for :admins
  devise_for :users, controllers: {registration: "registrations"}
  resources :users, only: [] do
     post 'premium_to_standard' => 'users#premium_to_standard', as: :premium_to_standard
    post 'standard_to_premium' => 'users#standard_to_premium', as: :standard_to_premium

 end



  resources :wikis do
     resources :collaborators
   end

  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'welcome/index'
  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Air-plant-O-pedia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <ul class="nav nav-tabs">
        <li class="nav-1"><%= link_to 'Plantipedia', root_path %></li>
        <li class="nav-2"><%= link_to 'Forest of Air Plants', wikis_path %></li>
        <li class="nav-3"><%= link_to 'New Air Plant', new_wiki_path if policy(Wiki).new? %></li>

        <div class="pull-right user-info">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %></strong> |
            <strong>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> -
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% if current_user.standard? %>
              | <strong><%= link_to 'Upgrade to Premium', new_charge_path %></strong>
            <% else %>
              | <strong><%= link_to 'Premium Status', new_charge_path %></strong>
            <% end %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>

        </div>
      </ul>

      <%= yield %>
      <!-- yield will render the template of the current controller/action -->
      <!-- So if you're on the "cars/show" page, it will render "views/cars/show.html.erb" << For example! -->
      <!-- adjust controller/actions according to what view you're looking at! -->

    </div><!--/end container-->
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>